Doc/lean inception
fga-eps-mds/2022-1-Alectrion-DOC pull request #95
Opened 2022-07-26 03:15 UTC by mv23c

## Modificações
Adição da documentação do brainstorm.
## _Issue_18/48
## Lista de controle:
- [x] Meu código segue a folha de estilos implementada
- [x] Meu _commits_ segue a política de commits do repo.
- [x] Minhas modificações requerem modificações na documentação atual.
- [x] Atualizei a Documentação.

2022-07-26 15:26 UTC, gleal17 requested changes

2022-07-26 15:26 UTC, gleal17 commented on docs/documentation/Lean Inception/brainstorm.md
> +
Adicionar captura de tela do mural para demonstrar a tarefa.

2022-07-26 15:56 UTC, mv23c commented on docs/documentation/Lean Inception/brainstorm.md
> +
Certo, vou resolver isso.

2022-07-26 16:16 UTC, mv23c commented on docs/documentation/Lean Inception/brainstorm.md
> +
Adicionei as imagens na pasta assets, que está dentro da pasta Lean Inception.

2022-07-26 21:56 UTC, lucasA27 commented on docs/documentation/Lean Inception/brainstorm.md
> +
Faltou adicionar as imagens no documento, se precisar de auxilio só chamar

2022-07-26 23:29 UTC, mv23c commented on docs/documentation/Lean Inception/brainstorm.md
> +
Certo, vou ver isso.

2022-07-26 23:55 UTC, mv23c commented on docs/documentation/Lean Inception/brainstorm.md
> +
Adicionei as imagens no arquivo.

2022-07-27 03:29 UTC, gleal17 approved these changes

2022-07-29 22:40 UTC, merged